commercetools.Sdk/Examples/commercetools.Api.ApmExample/Controllers/MeController.cs
using System.Threading.Tasks;
using commercetools.Api.ApmExample.Models;
using commercetools.Api.ApmExample.Services;
using commercetools.Base.Client;
using commercetools.Base.Client.Tokens;
using Microsoft.AspNetCore.Mvc;

namespace commercetools.Api.ApmExample.Controllers
{
    public class MeController : BaseController
    {
        public MeController(IClient client,
            MeServices meServices,
            CartServices cartServices,
            IUserCredentialsStoreManager userCredentialsStoreManager)
            : base(client, userCredentialsStoreManager, meServices, cartServices)
        {
        }

        public async Task<IActionResult> SignIn()
        {
            var customerProfile = await GetCurrentCustomerProfile();
            return View(new SignInCustomerViewModel(customerProfile));
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> SignIn(SignInCustomerViewModel model)
        {
            if (ModelState.IsValid)
            {
                var signInResult = await _meServices.SignIn(model.Email, model.Password);
                if (signInResult.IsValidCredentials)
                {
                    //after signin, the anonymous access token and refresh token are immediately invalid
                    //we need to get new access and refresh tokens with the password flow
                    _userCredentialsStore.StoreUserCredentialsAndClearToken(model.Email, model.Password);
                    return RedirectToAction("Index", "MyCart");
                }

                else
                {
                    model.ResetAfterLoginFailed();
                }
            }
            return View("SignIn", model);
        }

        public async Task<IActionResult> Logout()
        {
            await Task.CompletedTask;
            _userCredentialsStore.ClearCredentialsAndToken();
            return RedirectToAction("Index", "Home");
        }
    }
}

commercetools.Sdk/Examples/commercetools.Api.ApmExample/Views/Me/SignIn.cshtml
@model commercetools.Api.ApmExample.Models.SignInCustomerViewModel
@{
    ViewData["Title"] = $"Sign In";
    Layout = "_Layout";
}
<div class="text-center">
    @using (Html.BeginForm("SignIn", "Me", FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        <div class="container register">
            <div class="row">
                <h3>Login as a Customer</h3>
            </div>
            <div class="login-form">
                <div class="row form-group">
                    @Html.TextBoxFor(e => e.Email, new {@class = "form-control", placeholder = "Your Email *", required = true})
                    @Html.ValidationMessageFor(e => e.Email)
                </div>
                <div class="row form-group">
                    @Html.PasswordFor(e => e.Password, new {id = "password", @class = "form-control", placeholder = "Password *", required = true})
                    <span id="result"></span>
                    @Html.ValidationMessageFor(e => e.Password)
                </div>
                <div class="row">
                    <input type="submit" class="btnLogin" value="Login"/>
                </div>
                @if (Model.FailedLogin)
                {
                    <br>
                    <div class="row alert-danger">
                        Email or Password is Incorrect
                    </div>
                }
                @if (Model.EmailNotVerified)
                {
                    <br>
                    <div class="row alert-danger">
                        Please verify your email first
                    </div>
                }
            </div>
        </div>
    }
</div>